name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Navigate to repo
        run: cd $GITHUB_WORKSPACE

      - name: Set node version to v14.2.0
        uses: actions/setup-node@v1
        with:
          node-version: 14.2.0

      - name: Install deps
        run: npm install

      - name: Bootstrap Docs Engine
        run: |
          mkdir .docs
          npm run ghactionsbootstrap

      - name: Build
        run: npm run build

      - name: Publish
        uses: cloudflare/wrangler-action@1.2.0
        with:
          apiKey: ${{ secrets.CF_API_KEY }}
          email: ${{ secrets.CF_EMAIL }}
